"""
Per-pair Sharpe filter.

Reads scripts/backtest_trade_log.csv (from your 375-pair run), computes
per-pair metrics including net P&L after commission, Sharpe ratio, and
trade count, then filters to only pairs with demonstrable edge. The output
is a Python list you can paste directly into app/pairs_universe.py or main.py.

Run from project root:
    python scripts/filter_pairs.py
"""

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import warnings

warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
from pathlib import Path

TRADE_LOG_PATH = Path(__file__).parent / "backtest_trade_log.csv"
PAIR_RANKINGS_CSV = Path(__file__).parent / "pair_rankings.csv"
HIGH_CONVICTION_PY = Path(__file__).parent / "high_conviction_pairs.py"

COMMISSION_PER_SHARE = 0.005
MIN_TRADES = 5
MIN_SHARPE = 0.3
MIN_NET_PNL = 0.0

INITIAL_CAPITAL = 100_000


def load_trade_log() -> pd.DataFrame:
    if not TRADE_LOG_PATH.exists():
        print(f"ERROR: {TRADE_LOG_PATH} not found.")
        print("Run scripts/backtest.py first to generate the trade log.")
        sys.exit(1)
    df = pd.read_csv(TRADE_LOG_PATH)
    print(f"Loaded {len(df)} trades from {TRADE_LOG_PATH}")
    return df


def calc_pair_metrics(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for pair, group in df.groupby("pair"):
        group = group.copy()

        if "shares_a" in group.columns and "shares_b" in group.columns:
            commission = (group["shares_a"].fillna(0) + group["shares_b"].fillna(0)) * COMMISSION_PER_SHARE * 2
        else:
            commission = 5.0

        net_pnl_series = group["pnl"] - commission
        net_pnl_total = net_pnl_series.sum()
        trades = len(group)

        wins = (net_pnl_series > 0).sum()
        win_rate = wins / trades * 100

        returns = net_pnl_series / INITIAL_CAPITAL
        mean_r = returns.mean()
        std_r = returns.std()
        sharpe = (mean_r / std_r) * np.sqrt(252) if std_r > 0 and trades >= 2 else 0.0

        avg_pnl = net_pnl_series.mean()
        best_trade = net_pnl_series.max()
        worst_trade = net_pnl_series.min()

        reasons = group["reason"].value_counts().to_dict()

        rows.append(
            {
                "pair": pair,
                "trades": trades,
                "net_pnl": round(net_pnl_total, 2),
                "win_rate_pct": round(win_rate, 1),
                "sharpe": round(sharpe, 4),
                "avg_trade_pnl": round(avg_pnl, 2),
                "best_trade": round(best_trade, 2),
                "worst_trade": round(worst_trade, 2),
                "dollar_stops": reasons.get("dollar_stop", 0),
                "targets": reasons.get("target", 0),
                "coint_broke": reasons.get("cointegration_broke", 0),
            }
        )

    return pd.DataFrame(rows).sort_values("sharpe", ascending=False)


def filter_high_conviction(ranked: pd.DataFrame) -> pd.DataFrame:
    return ranked[
        (ranked["trades"] >= MIN_TRADES)
        & (ranked["sharpe"] >= MIN_SHARPE)
        & (ranked["net_pnl"] >= MIN_NET_PNL)
    ].copy()


def write_outputs(ranked: pd.DataFrame, high_conviction: pd.DataFrame):
    ranked.to_csv(PAIR_RANKINGS_CSV, index=False)
    print(f"\nFull ranking saved to: {PAIR_RANKINGS_CSV}")

    pairs = [tuple(row["pair"].split("/")) for _, row in high_conviction.iterrows()]
    lines = [
        '"""',
        "High-conviction pairs from backtest filter.",
        "Generated by scripts/filter_pairs.py",
        f"Filter: Sharpe >= {MIN_SHARPE}, trades >= {MIN_TRADES}, net P&L >= ${MIN_NET_PNL}",
        f"Count: {len(pairs)} pairs",
        '"""',
        "",
        "CANDIDATE_PAIRS = [",
    ]
    for a, b in pairs:
        lines.append(f'    ("{a}", "{b}"),')
    lines.append("]")

    HIGH_CONVICTION_PY.write_text("\n".join(lines))
    print(f"High-conviction pairs saved to: {HIGH_CONVICTION_PY}")
    print("Copy CANDIDATE_PAIRS from that file into app/pairs_universe.py or main.py")


def main():
    df = load_trade_log()

    print("\nComputing per-pair metrics with commission deduction...")
    ranked = calc_pair_metrics(df)
    high_conviction = filter_high_conviction(ranked)

    print("\n" + "=" * 70)
    print("TOP 20 PAIRS BY SHARPE (after commission)")
    print("=" * 70)
    print(
        ranked.head(20)[
            ["pair", "trades", "net_pnl", "win_rate_pct", "sharpe", "avg_trade_pnl", "dollar_stops", "targets", "coint_broke"]
        ].to_string(index=False)
    )

    print("\n" + "=" * 70)
    print(f"HIGH-CONVICTION PAIRS (Sharpe>={MIN_SHARPE}, trades>={MIN_TRADES}, net P&L>=${MIN_NET_PNL})")
    print("=" * 70)

    if high_conviction.empty:
        print("NO pairs passed the filter with current settings.")
        print("Options:")
        print(f"  1. Lower MIN_SHARPE (currently {MIN_SHARPE})")
        print(f"  2. Lower MIN_TRADES (currently {MIN_TRADES})")
        print("  3. Run param_sweep.py first, then re-run backtest.py, then re-run this script")
        print()
        print("Bottom 5 pairs by Sharpe (worst — avoid these):")
        print(ranked.tail(5)[["pair", "trades", "net_pnl", "sharpe"]].to_string(index=False))
    else:
        print(
            high_conviction[["pair", "trades", "net_pnl", "win_rate_pct", "sharpe", "avg_trade_pnl"]].to_string(
                index=False
            )
        )
        print(f"\n{len(high_conviction)} pairs passed the filter")
        print()
        print("Worst pairs to AVOID in live trading:")
        worst = ranked[ranked["trades"] >= MIN_TRADES].tail(5)
        print(worst[["pair", "trades", "net_pnl", "sharpe"]].to_string(index=False))

    write_outputs(ranked, high_conviction)


if __name__ == "__main__":
    main()
